name: Generate Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Cho phép bạn bấm nút chạy thử ngay lập tức

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Streak Stats
        uses: denvercoder1/github-readme-streak-stats@v1.5.0
        with:
          github_username: jerryphandev
          theme: tokyonight
        env:
          # Sử dụng Token bạn vừa tạo để lấy dữ liệu repo Private
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update streak stats" || exit 0
          git push